### ISSUE TITLE
Long shutdown time

### ISSUE THREAD

**Issue by basarevych** [robconery/massive-js#105]
I am running the following script:
```javascript
var massive = require('massive');

massive.connect({ connectionString: 'postgresql://pean:pean@localhost/pean' }, function (err, db) {
    if (err)
        process.exit(1);

    console.log('done');
});
```

It prints "done", then hangs for about a minute and only then terminates. Is there anything I can do to shut it down immediately?

**Comment by xivSolutions** [comment]
It's not 100% clear what you're trying to do here. Are you trying to write 'done' to the console if an error occurs? If so, you need to wrap the `console.log('done')` in curly braces as part of the `if()` block. 

Otherwise, if you are trying to write 'done' to the console as part of the 'happy path', and then exit, you will also need to exit the process as part of your happy path (generally using the "success" code of 0):

```javascript
if(err) { 
  process.exit(1);
}

// do some stuff with your data, call other functions - the work your application does...

console.log('done');
process.exit(0);

```

Note that generally, you are going to load up a reference to db and cache it somehow for use during the entire application lifecycle (also see the express example in the README as one example, if you are using express):

```javascript
var massive = require('massive');
var myDbInstance;
massive.connect({ connectionString: 'postgresql://pean:pean@localhost/pean' }, function (err, db) {
  if (err) {
    process.exit(1);
  }
  myDbInstance = db;

  // do moar work here with the db...

  console.log('done');
});
```

**Comment by basarevych** [comment]
Yes, I was expecting it to print "done" as success path and just exit immediately. Didn't know process.exit() was required here.

It's not the real script i'm working on. I just wanted to understand why it takes massive so long to shut down. Thank you for clarification.

**Comment by xivSolutions** [comment]
Node, and (to a certain extent, by association) Massive, are primarily expected to be used in a web server context. Meaning, more as a continually running service, rather than a process which runs, does some work, and exits. Therefore, the general use case will see Massive spun up, and the instance "kept alive" to service incoming requests. 

It's not the *only* use case for either Node, or Massive, but it is the common one. Therefore, in your example, Node is waiting for the next call to be made, and eventually times out (this is a non-technical explanation, possibly short on detail, but correct in spirit).
