### ISSUE TITLE
Support for io.js v3.0.0

### ISSUE THREAD

**Issue by vertiman** [robconery/massive-js#110]
Looks like a library Massive depends on, deasync, is not compatible with iojs.  Any thoughts on whether it can be replaced?

**Comment by xivSolutions** [comment]
deasync provided the needed sync capabilities better for our purposes than other libraries. I can;t speak for Rob, but Massive is, in fact, a Node-based library. Without stepping into the "schism" around all that, I think you're welcome to see if you can find something which works as well. If you do, let us know (or shoot us a PR!). 

All that said, deasync is in a rather "bleeding edge" state as I recall, and may evolve, or be abaondoned (or be made compatible with io.js). 

I think we are open to feedback, but when I was digging around trying to find a clean way to wrap some things up, deasync was by far the easiest to use.

**Comment by vertiman** [comment]
the concept of de-async seems so foreign in node/js.  Keep in mind iojs is the next node, it's being merged/finalized as we speak.

what are you using deasync for?  I'll poke around in the code and see if I can come up with something and help!

**Comment by xivSolutions** [comment]
I originally wanted a Sync "load" method, so one would have the option of letting a host application bootstrap without diving immediately into nested callbacks. When Massive spins up, it loads a bunch of stuff and caches it. It seemed like there were cases where this might be attractive. 

Rob added a bunch of additional sync methods, I am guessing for use with his Meteor.JS stuff (but I could be wrong). It is a node-based application, but there are cases where some sync love is not a bad thing. So long as you are intentional about it. 

We'd love the help! :-)

**Comment by robconery** [comment]
A growing use case for Node is as a utility tool - not just as the main executor for a web site/API. In some cases people use it for simple scripting of "things" - like data analysis and loading/unloading of sample/analytical data. This used to be the sole domain of Python - but more people are turning to Node because it's so simple to use.

So, Massive has sync abilities in there to accommodate. Given that I made this thing for me, mostly, I put it in there :). I hear you about it being "foreign" to Node - and I'm a very big advocate against doing things synchronously - but there are times when it just needs to be done (like when your app starts and you want a Massive instance).

I'm not going to implement changes for a future version of something - if Node bumps and deasync breaks, then we'll deal with it when it happens.
