### ISSUE TITLE
Find without limit in loop causes process out of memory

### ISSUE THREAD

**Issue by jwhitmarsh** [robconery/massive-js#160]
I've written a simple test script to compare performance between massive.js and sequelize (which massive was doing incredibly well in until this!) that does a find without a limit, 100 times. I'm doing a find on a table with ~200,000 records in it and after the 14th loop (every time) it throws 
```
<--- Last few GCs --->

   27791 ms: Scavenge 1410.8 (1457.0) -> 1410.8 (1457.0) MB, 16.9 / 0 ms (+ 1.8 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   28618 ms: Mark-sweep 1410.8 (1457.0) -> 1409.9 (1457.0) MB, 827.7 / 0 ms (+ 2.8 ms in 2 steps since start of marking, biggest step 1.8 ms) [last resort gc].
   29426 ms: Mark-sweep 1409.9 (1457.0) -> 1409.8 (1457.0) MB, 807.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x76c271b4629 <JS Object>
    1: parseDate [/Users/jwhitmarsh/src/massive-test/node_modules/massive/node_modules/pg/node_modules/pg-types/node_modules/postgres-date/index.js:~8] [pc=0x32f6cf6679b] (this=0x3db47f92c7a1 <JS Array[9]>,isoDate=0x2078d2b89419 <String[26]: 2015-12-26 19:04:44.406+00>)
    2: new constructor [0x76c271041b9 <undefined>:~1] [pc=0x32f6d00d503] (this=0x2078d2b89471 <JS Object>,parsers=0x3db47f92c7a...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6
```

Obviously this is not a real world scenario so I wouldn't make it a priority! but I thought it might be useful if it's pointing to some memory leakage somewhere?

**Comment by robconery** [comment]
It would be helpful to actually see your code...

**Comment by robconery** [comment]
That came out a little shorter than I intended - sorry in the middle of a few things :).

So, if I understand the issue here: you're doing a find without limit, so pulling 200,000 records into memory and you're running out of memory. You didn't say explicitly but I'm guessing Sequelize didn't cause the error?

I haven't looked at their code but I'll guess it's because they utilize streaming for larger queries - which is a good idea *always* for anything over a few hundred results. You can have Massive stream things by adding `{stream: true}` to your query options:

```js
db.users.find({company_id : 12}, {stream:true}, function(err,stream){

  stream.on('readable', function(){
    var user = stream.read();
    //do your thing
  });

  stream.on('end', function(){
    //deal with results here
  });
});
```

This will keep your connection open longer and could use up the pool (depending on what you're doing). Give this a try and see what happens.

Finally, if there's a memory issue it's likely at the driver level. We close off every connection after execution:

https://github.com/robconery/massive-js/blob/master/lib/runner.js#L40

We used to have pooling enabled here but it seemed... buggy - the release never happened as we expected so we just went back to straight querying and it hasn't really caused issues.

**Comment by jwhitmarsh** [comment]
No worries, I wasn't sure if the code would be useful or not (since it's just a simple async loop):

```
function maGetAll(i, next) {
  console.time('maGetAll' + i);
  db.apps.find({}, function(err) {
    if (err) {
      return fail(err);
    }
    console.timeEnd('maGetAll' + i);
    next();
  });
}

function many() {
  async.timesSeries(100, function(i, next) {
    //szCreate(i, next);
    //maCreate(i, next);

    //szGetAll(i, next);
    maGetAll(i, next);
  }, function() {
    process.exit();
  });
}
```

I'm never actually doing anything with the results so presumably it's being held in memory somewhere, i'm just not sure where... 

But it sounds like it's more of an issue with my loop rather than the library?

**Comment by robconery** [comment]
Well, hard to say really. Pulling 200K records repeatedly and seeing disastrous results really isn't surprising - as you can imagine Massive can't handle memory for you (short of making sure the connection is killed).

Give stream a try.
