### ISSUE TITLE
folder name vs table name

### ISSUE THREAD

**Issue by jney** [robconery/massive-js#172]
i would find it a very conveniant way to name my folders like my tables.
so i could call it `db.myTable.myQuery`
the problem is : folder can't be called like table. if a folder is named after a table name, function like `save` aren't accessible. is it the expected behaviour ?

**Comment by dmfay** [comment]
Yes, that's by design. There's only one `db` namespace and tables are loaded in before folders/scripts, so if there are naming collisions the latter will win out. If that's how you prefer to organize your scripts, the easiest thing to do is to prefix your folder names -- so `db.tablename` refers to the table itself, and `db._tablename` or some such is a collection of scripts that operate on the table.
