### ISSUE TITLE
materialized view

### ISSUE THREAD

**Issue by jney** [robconery/massive-js#177]
i'd like to do `db.view.find` with a materialized view, but it doesn't seem to work

**Comment by robconery** [comment]
Some detail here would help.

**Comment by jney** [comment]
sorry rob it was actually a question for confirmation if views (materialized or not) are supported. 
i've got a materialized view called `stores` and when i call it 

```
db.stores.find({field : '0000-0000-0000-000'}, function(err,stores){});
```

i wished it would be supported as tables are, but an error says, it can't call `find` on `null` value

**Comment by robconery** [comment]
No prob :) - I could swear @dmfay added support for views...

**Comment by dmfay** [comment]
Materialized views aren't part of the ANSI standard so `information_schema.views` doesn't cover them, unfortunately. Should be possible to make `lib/scripts/views.sql` query the system catalogs (`pg_views` and `pg_matviews`) instead, since we don't care about key information, but I don't know if I'll be able to get to it this week.

**Comment by dmfay** [comment]
Thought I'd give it a shot while waiting on code from someone else, and that turned out to be pretty much all that was needed.

**Comment by jney** [comment]
sure.
thanks
