### ISSUE TITLE
Simple transactions

### ISSUE THREAD

**Issue by n321203** [robconery/massive-js#208]
I know transactions have been discussed before (#81). However, I did a "minimal implementation" of transaction handling that I would like to show, just to see if you think this is something we can build on? Do you think the idea is sound? 

There is no promises/async library involved. The implementation is simply setting a flag that keeps track if we're in a transaction or not, and supply the right pg-connection to the query runner. 

I have done some quick testing but don't wanna put to much time on it if the whole idea turns out to be flawed. 

I made a PR here: #207 

Also: Massive.js is awesome!

**Comment by dmfay** [comment]
I think I see a problem, unfortunately -- haven't pulled the code to test myself but it looks as if once you've opened a transaction you can't do anything outside it until it's finished because it makes the runner stateful.

I haven't looked at adding transaction support in a while (priorities changed) but at this point I think either actually cloning or simulating cloning `db` is probably the way to go. End result would look something like this:

```javascript
db.tx.begin(function (err) {
    db.tx.mytable.insert(mydata, function (err) {
        if (err) { db.tx.rollback(); }
        else { db.tx.commit() };
    });
});
```

**Comment by robconery** [comment]
I added a comment on the PR but I'll add it here as well. Imagine this scenario:

```js
db.tx.begin(function (err) {
    db.tx.mytable.insert(mydata, function (err) {
       //User code goes BANG
        if (err) { db.tx.rollback(); }
        else { db.tx.commit() };
    });
});
```

If the thread exits (which it would) the connection pool would be gone as well and, ideally, the transaction voided in PG (which is per connection). However, to get around this, Joe Coder would put this is a try/catch - you don't want a tx to die on you yes?

The problem is that the catch block would need to release/rollback or else we end up with a pending transaction stuck on a connection that's put back into the pool, which would be a roving chaos monkey.

It *is possible* to do this correctly - but at the end of the day it's just simpler to add "BEGIN" and "COMMIT" to your query chain by hand - or better yet to just use a SQL file.

**Comment by n321203** [comment]
@robconery: "The problem is that the catch block would need to release/rollback or else we end up with a pending transaction stuck on a connection that's put back into the pool, which would be a roving chaos monkey" 
– Yup, that would cause trouble. But I think in your example, the connection would never be returned to the pool, because runner.js would never call `done()` (since Joe Coder didn't rollback). Instead it would be kept open, unavailable for other clients to use. 

"it's just simpler to add "BEGIN" and "COMMIT" to your query chain by hand - or better yet to just use a SQL file"
– Yes, a SQL file is probably the best way in many cases. My use case is that I'd like to be able to quickly update multiple tables atomically without having to write a separate sql file. 
I don't understand what you mean with the query chain – surely writing
```
db.query("BEGIN", ...)
db.table.save( ... )
db.query("COMMIT") 
```
isn't a good idea? The connection is returned to the pool after each query.


@dmfay: Unless the runner is implemented as a singleton, this shouldn't be a problem? Or maybe I misunderstand you?

**Comment by dmfay** [comment]
Thanks to Node's module caching, the runner _does_ have singleton-like characteristics even if it doesn't meet the complete technical definition. Try changing the `before()` hook in one of the testcases to open a transaction and log whether you're in one or not from the runner, then run `mocha test` -- you'll see that everything from that point onward is executed within the transaction even as the succeeding testcase modules re-`require` and reconnect Massive.

**Comment by n321203** [comment]
@dmfay – doh!:stuck_out_tongue_closed_eyes: Then this approach won't work. Closing it.

**Comment by robconery** [comment]
>  But it is unavailable for others, so we'll avoid the chaos monkey :)

@n321203 No, that's not the point. The transaction is bound to the connection and, given that it's part of a pool, the connection will go *back into the pool* if Joe Coder calls `done()` - it's at that point that we have some big trouble. If/when that connection is handed back out you'll get a "cannot perform query with an open transaction. Please commit or rollback". This is a gruesome runtime error that yours truly has run into before.

> My use case is that I'd like to be able to quickly update multiple tables atomically without having to write a separate sql file. I don't understand what you mean with the query chain – surely writing

It's code in a file no matter where you put it; abstracting something like this is not necessary as SQL has the best facility for "updating multiple tables atomically". Just create a SQL file and call it from JS - simple stuff.
