### ISSUE TITLE
Run query with inserted elements returns null

### ISSUE THREAD

**Issue by RayLLiu** [robconery/massive-js#230]
Hi, i have tried using different ways to run a sql query with inserted elements(See the following):
A. 
 db.testfile(['Action'], function(err, result) {
    console.log(result);
    res.send(result);
  });
With the "db" folder contains: testfile.sql and inside the testfile.sql i wrote:"SET SEARCH_PATH='moviedb';SELECT * FROM TOPICS where DESCRIPTION=$1;
"

This returns null.
A2
 db.testfile(['Action'], function(err, result) {
    console.log(result);
    res.send(result);
  });
i modified the sql file to be:"SET SEARCH_PATH='moviedb';SELECT * FROM TOPICS where DESCRIPTION='$1';" (single quotes added)

it returns null still.
B.
db.run("SEARCH_PATH='moviedb';SELECT * FROM TOPICS where DESCRIPTION=$1;",["Action"],function(err, result) {
    console.log(result);
    res.send(result);
  });

This returns null as well.

C.
 db.testfile(function(err, result) {
    console.log(result);
    res.send(result);
  });

This time i modified the sql file "SEARCH_PATH='moviedb';SELECT * FROM TOPICS where DESCRIPTION='Action';"
it returns:
[
  {
    "topic_id": 1,
    "description": "Action                                  "
  }
]

D. The worest solution i found is to create a dynamic query string:

  console.log(req.body.moviename + "n");
  var query = "SEARCH_PATH='moviedb';SELECT * FROM TOPICS where DESCRIPTION='" + req.body.topic_description + "');"
  console.log(query);
  db.run(query, function(err, result) {
    console.log(result);
    res.send(result);
  }); 
This time it works when front end give different "topic description"

Thank you very much.
Ray

**Comment by RayLLiu** [comment]
[myapp.zip](https://github.com/robconery/massive-js/files/201329/myapp.zip)
The attached file is the source code.

**Comment by xivSolutions** [comment]
Ok. As you mentioned in the [https://github.com/robconery/massive-js/commit/d939f7a18d82c31d24a59322ef00de89bc0f65f1#commitcomment-16944336](other thread), you have a database with schema. 

You really don't need `set search_path` here, because Massive (and, fortunately, sql) understand the notion of schema. So, to start, you can re-write your sql like so:

`SELECT * FROM moviedb.topics where DESCRIPTION=$1;`

From there, note the following - once you place params into your sql statement, the underlying node-postgres driver considers it to be a prepared statement, and it will not run, since the driver will not allow multiple sql commands within a single prepared statement. 

Which is the root of your problem here.

The fix above (explicitly specifying the schema using "dot" notation in your sql should fix this up straight away. 

On a final note, though, I mentioned that Massive itself also has the notion of schema. So you could skip the sql file if needed (in a case like this), and simply do this:

```js
db.moviedb.topics.where('description = $1', 'Action', function(err, res) { 
    console.log(res);
});
```

The README may be in need of a little updating, but most of the basics are there.

**Comment by RayLLiu** [comment]
Yay! It works! Thank you very much!
Ray
