### ISSUE TITLE
table findDoc ignores options

### ISSUE THREAD

**Issue by habermeier** [robconery/massive-js#233]
It'd be nice if I could pass in options to `findDoc`, such as, for example:

    findDoc({type: 'some_value'}, { order: 'id desc', limit: 5 })

And have that work.  Tracing down into it, it looks like `findDoc` ignores the additional options, unlike in the code for `find` (in queryable.js / prototype.find) -- lines 99 through 137.  It's unclear if there would be a problem with supporting  `db.stream`.  I've worked around it by just using `run` in my code, but it's not as nice (obviously).

**Comment by robconery** [comment]
Hmmm I see to remember having this problem and it was weird because we're dealing with documents wishing a table and the options would need to be handled in a special way. For instance, the order statement you have here *should work* because `id` is part of the table itself (all the JSONB stuff comes from `body`), however if you wanted to order on something else you would need to do it thus:

```sql
order (body ->> 'some_value')::integer desc
```

JSONB won't necessarily be ordered the way you like (for example with dates) so casting it is necessary. Anyway - what I'd like to know is: is this *failing* for you (as in an error) or is it just not working at all? You mention its ignored, but we *are* sending the options to the query:

https://github.com/robconery/massive-js/blob/master/lib/document_table.js#L127

So I'm a bit confused. @dmfay we don't have any tests for options and docs, but it would be nice to build some in if you have any time this weekend. I'm goofing around with v3 and can try as well.

**Comment by habermeier** [comment]
The query did not fail.  It just doesn't look at options.  I set a few breakpoints, and the options bubble on down but are not used in the later stages (from what I can tell).  To get a feel for it, I looked at how `prototype.find` is implemented, and there seems to be specific code there to handle the options, but that code is doesn't get called when you go through findDoc, so the options just sit there ... and get ignored.

I'd say it'd be lovely if we could pass in options, and when it comes to order clauses inside the jsonb, I'd just document how to do it.  From a user perspective, if you show how you can do those things, I'm sure that would help a lot of others as well.

I'm just converting stuff over from dynamoDB (which is a terribly stunted document store, I might add)... and just happened to find postgres can now do jsonb, which is nice because I don't want to managing schemas for the support app I have to develop.  Long story short: it'd be nice to have some `options` support at minimum: (`order by id`, `limit`, and `offset`).  To sort inside the jsonb itself, maybe you just document how one would do that with some examples (like you just gave), and users have a way of dropping that in should they need to.

Still beats having to "roll your own all the way"...

**Comment by robconery** [comment]
Thanks - I'll have a look this weekend!

**Comment by dmfay** [comment]
@robconery yeah, I've only started to use the document functionality at all pretty recently. I'll take a stab at adding some tests if I have time soon.

**Comment by dmfay** [comment]
As it stands now, you can use `order` with `findDoc` but have to call out the field the way Rob described, using the JSON traversal operators from the `body` field. That might not be ideal, but it gets the job done.

Personally, I'm fine with that being the state of things: I've got some, for lack of a better term, hybrid document tables with a `body` but also various other fields, and it's handy to be able to look at those either way as the situation requires. If we tried to parse and process the order string to turn `myfield desc` into `body->>'myfield' desc`, there isn't a good way to make sure myfield is *really* on `body`.
