### ISSUE TITLE
Generators for REPL

### ISSUE THREAD

**Issue by robconery** [robconery/massive-js#25]
Would be nice to have the ability to stub out more complicated queries (such as adding a Full Text field with an index) in the REPL. In addition, FT query syntax and any other helpful stuff to get people off the ground writing SQL.

**Comment by xivSolutions** [comment]
Do you mean stub out sql-ish templates + suggestions on-screen in the REPL, or take some guided inputs and generate scripts/save in a queries folder (or both)?

Got an example of the REPL input you envision, and idea for output?

**Comment by robconery** [comment]
Both really - the REPL could be a huge tool for helping people out with SQL etc. I’m going all over the place with ideas - let’s hash a few out :).

First idea is having Massive help you develop your DB. So running something like “initdb” would create a db directory and an initialization script (maybe in /schema/tables or something). It could then stub out a nice users table for you - something you could use as a guide to learn how to run CREATE TABLE scripts and use tsvector, etc.

There could be a number of commands in there - like setting up a table for searchability (adding a search(tsvector) column, indexing it with GIN, creating a trigger). Outputting common operations (JSONb searches) etc.

In a way - like Rails generators except for Postgres queries :).

We could probably use Underscores templating to get started if we wanted - but figuring out a nice mechanism that underlies generation would be neat :).



On March 10, 2015 at 1:42:18 AM, John Atten (notifications@github.com) wrote:

Do you mean stub out sql-ish templates + suggestions on-screen in the REPL, or take some guided inputs and generate scripts/save in a queries folder (or both)?

Got an example of the REPL input you envision, and idea for output?

**Comment by xivSolutions** [comment]
This is an interesting one. Hard to find the sweet spot between making helpful utility functions that get your SQL made mo 'easier, and making something where you're typing some convoluted bastard-hybrid-mongrel SQL/JS into a terminal instead of just...writing some SQL. 

Pushing out helpful example/template SQL to the terminal is easy enough ("reminders" - like you said "how do I create a table again?") but on the other hand that type of thing is all over the web. And, if someone is savvy enough to be choosing PG as a database, they probably have SOME clue . . .

Definitely like the helpers for adding search and JSONB stuff though. I still suck at all that, so that's a good sign we may be onto something.

**Comment by trentrichardson** [comment]
An idea for enhancement might be a super light weight migration utility. Since massive already likes sql files it seems like it would be an easy routine to do up and down migrations. The user creates the actual sql files (not generated like big ORMs). 

Massive would just need to keep up with the current migration level and just `migrate latest` or `migrate 2` and run each sql file to migrate the db to that level:

1_down.sql
1_up.sql
2_down.sql
2_up.sql
3_down.sql
Etc...

This approach isn't completely thought through, but after using the library a bit this came to mind and seemed to be related to this.

**Comment by dmfay** [comment]
Migrations are the sort of thing I'd much prefer to handle with a dedicated utility, to be honest. There's already [node-pg-migrate](https://github.com/theoephraim/node-pg-migrate) and [node-db-migrate](https://github.com/db-migrate/node-db-migrate), among others, and even if they might lack certain features or be a bad fit for some use cases, it's highly unlikely a quick&dirty effort to add a migration module to Massive would produce anything _more_ generally useful. I'm not a fan of the Swiss army knife approach -- better to do one thing and do it well imo.

**Comment by robconery** [comment]
Yep - there are better tools out there and, frankly, I hate migrations in general :).
