### ISSUE TITLE
jsonb and excel functionality

### ISSUE THREAD

**Issue by swinston100** [robconery/massive-js#259]
Hi @robconery 

Thanks for the great query tool. I'm having an issue saving JSON into a table:

https://github.com/craigkerstiens/json_node_example/issues/2

I've got around it by doing:

```js
    db.saveDoc("test", excel[0], function(err,res){
      if(err){
        console.log(err);
        complete();
      }
      else {
        console.log(res);
        complete();
      }
    });
    
    function complete(){
      for(i = 1; i < excel.length; i++) {
        db.saveDoc("test", excel[i], function(err,res){
          if(err){
            console.log(err);
          }
          else {
            console.log(res);
          }
        });
      };
```

But I think I am missing something very fundamental in my understanding of massive. Can you help me out please?

Thanks

Steven

**Comment by dmfay** [comment]
Is this about the 'relation already exists' error message in your comment on the other issue or is there something else you're seeing? If the former, make sure `createDocumentTable` is only being invoked once.

**Comment by swinston100** [comment]
@dmfay - yes it is about that issue.
When calling `saveDoc` it's probably also invoking `createDocumentTable`.
Which leads me to another question...
How do you use massive to get data into a table (apart from using saveDoc)?

And how do I create a table with a specific model?

`db.createDocumentTable('test (id serial primary key, body jsonb)', function(err, res) {  });`

Is obviously not the correct syntax.

Thanks!

**Comment by dmfay** [comment]
With the single exception of generating document tables (which have a fixed specification), Massive's design doesn't include any special functionality for modifying the structure of your database. You can emit arbitrary SQL, including `CREATE` and `DROP` statements, via `db.run` but that's the extent of it.

For basic questions, please see the [documentation](http://massive-js.readthedocs.io/en/latest/).

The specific problem you're having is likely due to `saveDoc` being in that for loop -- the function does create the table if it doesn't exist, but the fact of the table's existence is only recorded once it calls back; so if you're just iterating, the callbacks are going nowhere and you're working with the outdated db definition and it tries to create the table again each time. You have a couple of options here:

1. Create the table beforehand, and bulk insert the array:
```js
var items = excel.map(function (item) { return {body: item}; });

db.test.insert(items, function (err, rows) {...});
```

2. Use a library like [async](https://github.com/caolan/async) to insert row-by-row and handle the asynchronous callbacks.

**Comment by swinston100** [comment]
@dmfay - thanks so much, very helpful! Much clearer now :+1:
