### ISSUE TITLE
Refactor File Walker/Script Assignment

### ISSUE THREAD

**Issue by xivSolutions** [robconery/massive-js#29]
Pull out the function assignment from the file walking bits. 

@robconery Earlier on, you had thought you wanted to fie walk/Function assignment pulled out of index.js. You have since moved it back. Did you want to keep it there now, or did you still want to pull it out?

It's two functions now - easier to read/understand, but potentially dirtying up index.js with noise. 

What say you?

**Comment by robconery** [comment]
Looks good - did you pull out the try/catch for any reason? It'll throw if the directory doesn't exist (which I was oblivious to for some reason) so we should allow for that.

**Comment by xivSolutions** [comment]
No try catch there when I got to it (unless I'm missing somethinig). I mainly just pulled it straight out, then diddled about with the closure aspects of it...but if that's the case, we should put it back!

**Comment by xivSolutions** [comment]
Oooh. That's weird. And concerning. I see where you mean now, and I know how it got missed. Was working in a stale copy at first, then pasted. Fixing.

**Comment by robconery** [comment]
Cheers - merge it in when you’re done and thanks!



On March 8, 2015 at 7:51:33 AM, John Atten (notifications@github.com) wrote:

Pull out the function assignment from the file walking bits.

@robconery Earlier on, you had thought you wanted to fie walk/Function assignment pulled out of index.js. You have since moved it back. Did you want to keep it there now, or did you still want to pull it out?

It's two functions now - easier to read/understand, but potentially dirtying up index.js with noise.

What say you?
