### ISSUE TITLE
countSync returns a string

### ISSUE THREAD

**Issue by ianp** [robconery/massive-js#290]
For example:
```js
db.sessions.countSync({id: 5})
'0'
```
Which is awkward of you're trying to be a good JS citizen and use `===` instead of `==`.

**Comment by dmfay** [comment]
Postgres uses 64-bit ints by default including for `count`, but JavaScript only supports 32-bit. Since we (and the node-pg team) can't guarantee that nobody's database will need the extra int space, `int8`s get converted to strings and the job of parsing it is on the user.

If you're running 2.4 you can pass the `parseInt8` connect option like so:

```javascript
massive.connect({
      connectionString: helpers.connectionString,
      defaults: {
        parseInt8: true
      }
    }, ...);
```

Otherwise use the driver-level option detailed [here](https://github.com/brianc/node-pg-types#use).

**Comment by ianp** [comment]
Ah, OK, that makes sense, thanks for the clarification.

FWIW the sync stuff is just in unit tests and I'm in the process of getting rid of it.
