### ISSUE TITLE
'bind message supplies 2 parameters, but prepared statement "" requires 1'

### ISSUE THREAD

**Issue by benjie** [robconery/massive-js#320]
If you try and update rows that are not null, the query fails with above error. e.g.

```js
db.table.update({'foo !=': null}, {foo: 27}, ...)
```

The reason for this seems to be that this line of code is a little naïve, and doesn't realise that the "where" clause for that parameter doesn't require an argument:

https://github.com/robconery/massive-js/blob/23e821af7856a12d81e7be3c98243f70c99c5b53/lib/table.js#L101

**Comment by xivSolutions** [comment]
Hmmm...this is an interesting one. It appears you are correct sir. Looks like we may need to do some re-organizing of the code there so that param values for such statements aren't pushed into the array. I can look at this after work, unless you want to take a stab at it, or unless @dmfay gets to it in typical lightening-fast fashion ;-)

Nice catch :-)

**Comment by dmfay** [comment]
I've been holding off on doing much until the Promises implementation starts to take shape -- not a lot of point in getting into something big when a change on that scale is imminent. But this, yeah, this is a problem.

**Comment by xivSolutions** [comment]
@dmfay  - Yeah, I know Rob's been pretty busy with his book, and I've been really tied up with a feature at work. Sigh. Really want to get rolling on that.

**Comment by benjie** [comment]
Thanks for the quick turnaround! 👏
