### ISSUE TITLE
Specify order-by column and sort order (ASC, DESC) in SQL files

### ISSUE THREAD

**Issue by deo79** [robconery/massive-js#336]
Is there currently a way to pass parameters to SQL files to specify what column to sort by and the sort order?

For order-by clauses, I think I could do a CASE/WHEN, however that doesn't help me change from ASC/DESC.

**Comment by dmfay** [comment]
Not now, and, I'm afraid, not ever. Prepared statements bind parameters rather than interpolate them (and with good reason -- the latter is how you open yourself up to SQL injection!). The only halfway realistic implementation involves sorting the final result set outside the database, which would be terrible for a whole host of reasons.

Think about using a view instead, if possible. Massive treats those identically to tables, save of course that they're read-only, so you'd be able to pass sort options to `db.myview.find()`.

**Comment by deo79** [comment]
Thanks for responding.  I definitely get what you're saying.  A view it is then.  It's a bummer because it limits the usefulness of SQL files, which is a great feature of Massive.
