### ISSUE TITLE
Question: is there any mitigation against SqL injection

### ISSUE THREAD

**Issue by nmccready** [robconery/massive-js#46]
Cool library, I am investigating this and I want to know it's limitations. Ofcourse the web api layer can handle parameter checking; but is there anything or any plans for safety checks for injections into existing scripts in the db folder?

**Comment by robconery** [comment]
Thanks :). Your question is a bit confusing, but I'll see if I can answer with *I think* you mean.

SQL Injection is handled by the driver. All you need to do is be sure to use a parameter, like so:

```
select * from table where name=$1;
```

That `$1` marks the statement for inclusion of a parameter. Massive is built on top of this idea. If you use SQL in files, you'll need to be sure to write you SQL like this. Then you can call it (assuming your file is called myQuery.sql) like this:

```
db.myQuery('joe', ...)
```

The value "joe" will be added to the query as a parameter, which is sanitized by the driver.

Your question, the way it's phrased, makes me wonder what you mean by *injections into existing scripts in the db folder*. If someone had access to your box and dumped a SQL file in the /db folder and restarted your server - yes that's a problem. I don't think that's what you mean, however, because that would be a very silly way of attacking your server.

The next thing that confused me is *the web api layer can handle parameter checking*. No, it can't. You really shouldn't try and sanitize input yourself, otherwise it ends up going in the database. Let the driver do it, almost as a rule (which is what we do). The driver knows the right escapes, don't do this yourself.

In terms of *plans for safety checks*, I don't build unsafe stuff as a rule - which is not to say that a vulnerability can't be found. Merely that I did my very best to be sure I did the bare minimum and SQL Injection is part of that.

**Comment by nmccready** [comment]
Thanks for the quick response. I'll get back to you w/ better questions/examples when I'm not on a mobile device and exhausted.

**Comment by robconery** [comment]
The issues list is not the place for questions/examples; better if you send an email or (preferably) read through the test suite/README and see what you can find.
