### ISSUE TITLE
db.xxxx.save with no PK is attempting UPDATE rather than INSERT 

### ISSUE THREAD

**Issue by cwgabel** [robconery/massive-js#55]
see https://gist.github.com/cwgabel for code, logs, ddl.

**Comment by xivSolutions** [comment]
Is there a sequence created for your user_code column? It looks like you have specified an integer type, and set up a constraint, but I think without explicitly creating a sequence or declaring the user_code column as a serial type (which causes the sequence to be created), your default won't work?

Not sure if that's related, and I'm on the road at the moment. But if you are not explicitly creating a sequence for the user_code column, I'm wondering if this is a contributing factor?

**Comment by cwgabel** [comment]
I have user_code tied to a default value using users_sequence (see the gist for the DDL). The sequence must be working for the INSERT that did work in the code (via db.run) for it did not contain a user_code value (per DEFAULT). I added the db.run just to make sure I could INSERT correctly and help alleviate reason as to why the db.users.save is failing.

**Comment by xivSolutions** [comment]
Unless I am totally missing something, the sequence will not be created using the DDL you have provided, unless you are creating it somewhere else using `CREATE SEQUENCE`. In fact, the DDL you reference fails in pgAdmin3 because the sequence doesn't exist. 

Still seems like Massive should be trying (and, worst-case, failing) to execute `INSERT` and not `UPDATE`, tho...

Just as a sanity check for me, can you drop/create the table, and try using:

```
CREATE TABLE users_test
(
  -- change this:
  user_code serial primary key not null,
  username character varying(15) NOT NULL,
  firstname character(15) NOT NULL,
  lastname character(15) NOT NULL,
  email character varying(100) NOT NULL,
  password character varying(100) NOT NULL,
  birthday date NOT NULL,
  provider character varying(15) NOT NULL,
  salt character varying(100) NOT NULL,
  created timestamp without time zone NOT NULL DEFAULT ('now'::text)::timestamp without time zone,
  -- ditch this:
  -- CONSTRAINT user_code_pk PRIMARY KEY (user_code),
  CONSTRAINT email_uix UNIQUE (email),
  CONSTRAINT username_uix UNIQUE (username),
  CONSTRAINT email_blank CHECK (email::text <> ''::text),
  CONSTRAINT firstname_blank CHECK (firstname <> ''::bpchar),
  CONSTRAINT lastname_blank CHECK (lastname <> ''::bpchar),
  CONSTRAINT users_password_check CHECK (password::text <> ''::text AND char_length(password::text) > 5),
  CONSTRAINT users_provider_check CHECK (provider::text <> ''::text)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE users_test
  OWNER TO postgres;

```

And then try running your Massive.js code?

In the tests, we use save with and without the PK, and it works as expected. I'm not saying you're wrong here (at all!) just trying to trouble shoot. I'll try to fire up something similar here when I get back to my hotel, and see what there is to see.

**Comment by cwgabel** [comment]
Thanks for looking at this. 

I got the same same thing with userstest.  Not sure what the update is all about.

Logs still show an update...

015-04-27 19:59:33 CDT 42P00ERROR:  inconsistent types deduced for parameter $1 at character 37
2015-04-27 19:59:33 CDT 42P00DETAIL:  text versus character varying
2015-04-27 19:59:33 CDT 42P00STATEMENT:  UPDATE "userstest" SET "username" = $1, "firstname" = $2, "lastname" = $3, "password" = $4, "birthday" = $5, "provider" = $6, "salt" = $7 
	WHERE "email" = $1 RETURNING *

**Comment by xivSolutions** [comment]
@cwgabel - Think I see the issue. 

If you pulled Massive down from NPM, that version is missing some recent fixes. Particular to your issue, #53 [Correct Join on Tables.sql Query to Return Single Row per Table](https://github.com/robconery/massive-js/issues/53) fixed a situation where more than one row was being returned as a table primary key. 

The issue is caused in part by your DDL, which specifies a Primary key, and two UNIQUE constraints. For some reason, Postgres considers these to be part of a primary key. Prior to the fix implemented in [THIS](https://github.com/robconery/massive-js/commit/591f78e8d21d90cd8c8cb848194a26a286b6c8bf) commit, the tables.sql query was returning all three columns as rows, and assigning the last (email) as the pk for your table. So, since Massive checks to see if the table pk is provided and has a value, it found both and assumed you are trying to UPDATE. 

Until we psuh an update to NPM, if you go into the `node-modules` directory, and change the `tables.sql` to THIS:

```
select tc.table_schema as schema, tc.table_name as name, kc.column_name as pk
from 
    information_schema.table_constraints tc
    join information_schema.key_column_usage kc 
        on kc.table_name = tc.table_name and
           kc.constraint_schema = tc.table_schema and
           kc.constraint_name = tc.constraint_name 
where 
    tc.constraint_type = 'PRIMARY KEY'
order by tc.table_schema,
         tc.table_name,
         kc.position_in_unique_constraint;
```
SHOULD fix the problem. 

I am curious about the UNIQUE constraints doubling up in the PK, though. Gotta go check the Postgres docs on this.

**Comment by cwgabel** [comment]
Thanks for your help, works great now.
