### ISSUE TITLE
Overriding existing table methods

### ISSUE THREAD

**Issue by mzedeler** [robconery/massive-js#62]
I tried (by accident) to override `db.user.insert` and got the error `bind message supplies 1 parameters, but prepared statement requires 2`.

The library should either treat it as an error if a built in method is overridden or behave as expected.

**Comment by robconery** [comment]
Let me see if I understand the problem(s): the first is that you overrode a generated routine and want Massive to stop you from doing that. The problem is Javascript doesn't have a facility for that - there's no way for Massive to know that you've done such a thing.

The second seems to be that you encountered a problem running your query - meaning that your SQL string has two parameters (`$1` and `$2`) but you only passed one parameter, so it didn't work. 

Did I get this right?

If so, what would you expect Massive to do in each case?

**Comment by xivSolutions** [comment]
@mzedeler  - It's hard to know exactly what's happening beyond the obvious here. The obvious is that your override of the generated `insert()` method attempts to perform an insert with a mismatch between expected parameter values, and actual parameter values. 

One of the handy things about JavaScript is that is allows you to bolt on new methods/properties ("overrides") etc.. to your heart's content, and will try to do what you tell it to. 

One of the challenges of Javascript is that it will allow you to bolt on new methods/properties ("overrides") etc. and will try to do what you tell it to *without complaining.*

In this case, it is doing almost exactly what you are asking - you added an override (intentionally or no) for an existing method which appears to build either a flawed SQL statement, or incorrectly matches parameter values to parameters specified. Massive attempts to execute, and Postgres itself complains to the PG library, which passes the error on up to Massive.

In any other language, (say, a strongly typed language such as C#) it is possible to create an override method which compiles, and executes without complaint from the compiler or runtime, and which still fails when it attempts to execute improperly constructed SQL against PG or any other database. 

In other words, it doesn't matter if the method is an override or not, it still needs to pass to the backing store a SQL statement with a matching set of params and values. If the parameter values don't match the parameters specified, you will get a similar error. 

Unless I am missing something, the problem is not that Massive allowed an "override" but that there is a bug in the code in the "override" method itself? There is no way Massive, or any other library, can protect you from attempting to execute SQL with a mis-match between parameter placeholders and parameter values beyond doing precisely what happened here. 

In other words, are you asking massive to warn you if a method in your own code attempts to override an existing method? Or are you asking massive to check what your override method does to make sure it is going to work correctly? The former is probably doable (though not practical, nor really necessary), the latter is not. If you choose to override a method, you do then need to make the code work properly.

Have we missed something?

**Comment by mzedeler** [comment]
Thanks for the very, very fast feedback. I'm somewhat overwhelmed. I'll reply soon.

![](http://www.everydaydevotions.com/wp-content/uploads/2015/01/surprise.jpg)
