### ISSUE TITLE
Add Capability to use Config File for Initialization Parameters

### ISSUE THREAD

**Issue by xivSolutions** [robconery/massive-js#66]
We have a number of possible config params one might pass in during the call to `massive.connect()`. We may want to have massive look for a config file for these if `.connect()` is called either without arguments, or with a `configFile` property specifying the path.

**Comment by AdrianRossouw** [comment]
That seems like something to leave up to the application, because it will know best how to manage it's configuration.

Also, It not entirely out of bounds that there might exist an application that has multiple massive instances. Any config file auto-loading would require jiggery pokery on the implementor's part.

**Comment by xivSolutions** [comment]
Yeah, the idea was to enable an application to specify one or more configure files by passing in a path/paths as described in the original comment. Meaning, a sensible default, easily overridden by the application if needed.

Point well taken, though. We appreciate all of this type of discussion :)

**Comment by robconery** [comment]
Closing this for now.
