### ISSUE TITLE
Add Massive class to exports

### ISSUE THREAD

**Issue by sheldonkwok** [robconery/massive-js#76]
For bluebird users, it's easier to promisifyAll the prototype instead of the class instance everytime

**Comment by robconery** [comment]
Help me understand this?

**Comment by SimonDegraeve** [comment]
Indeed would be nice to have support for Promise.

See [http://bluebirdjs.com/docs/api/promisification.html](http://bluebirdjs.com/docs/api/promisification.html).

**Comment by sheldonkwok** [comment]
"Most libraries can be promisified by requiring the library's classes (constructor functions) and calling promisifyAll on the .prototype. This only needs to be done once in the entire application's lifetime and after that you may use the library's methods exactly as they are documented, except by appending the "Async"-suffix to method calls and using the promise interface instead of the callback interface."

**Comment by robconery** [comment]
What is it about promises that gives you a better understanding/working-feel for Node and Javascript in general? Is it the "feeling" that things are synchronous? Honestly I'm not trying to be an ass here - I really want to understand what it is about promises that make people feel better.

Because at this point, that's what it is: *a feeling*. I'm all about a groovy API to make people feel happy - but promises don't do that in my opinion.

**Comment by SimonDegraeve** [comment]
Well, it is 2015. If people want to use Promise, just by adding one export to the module, they can. It is not a big deal.

I don't think, the "feeling" thing is pertinent here. For me it is just an abstraction like any others. If you use Express instead of Node HTTP Core, do you "feel" something? 

For me the selling point for Promise is the developer experience: cleaner code, centralised error handling, serial-parallel, etc... 
It is not about forgetting that the code with-in is async.

**Comment by sheldonkwok** [comment]
Yielding promises is already a supported feature in the latest versions of node so it would be nice to leverage this. I think it's a nice abstraction that makes async code easier to manage once you understand the concept. You don't have to use it but it's there and the concept is being improved on in es7 with "async/await."

**Comment by robconery** [comment]
As you can tell, I have a pretty strong opinion on promises - maybe it's because I used previous versions of Node.

> Well, it is 2015. 

That's not going to help this discussion. You're talking to a person who spends his days pushing people outside their comfort zones. I'm not scared of promises, *I simply don't like them*.

To be constructive - I'm OK with exporting the class in general. Would appreciate a PR so I can focus on an implementation rather than a philosophical debate.

**Comment by shawn-simon** [comment]
Ugh was about to try out this library then read your remarks in this thread...

**Comment by robconery** [comment]
@shawn-simon Yes you should forego any benefit because I dislike promises. That's how you should make a technical decision - entirely based on the project lead's opinions. If you have a differing opinion you're welcome to share it, but don't drop in and troll, that's bullshit.

**Comment by shawn-simon** [comment]
Sorry, didn't mean to derail your thread. However, as nice as this project looks it won't work with my promise-based JS architecture. I would encourage you to learn and understand promises since they make your code much, much better. They are a bit difficult to grasp at first, so I understand your reasonings.

**Comment by robconery** [comment]
LOL nice swipe couched in a seemingly thoughtful reply. Well done :).

Is this what you mean by making my code look better?
https://github.com/TryGhost/Ghost/blob/master/core/server/index.js#L125

Promises are horrible mate, an abstraction for a hobbled language that looks neat at first and then you end up with an awful mess when the shit hits the fan. Javascript is a lovely evented language - get used to it.
