### ISSUE TITLE
Transactions?

### ISSUE THREAD

**Issue by dmfay** [robconery/massive-js#81]
I saw an old closed issue where transaction support was mentioned as a future consideration ( #14 ). Is that still planned?

**Comment by robconery** [comment]
Sort of - I was just thinking about this myself. The simplest thing to do is just use a SQL file (which is encapsulated in a tx) and it also means we don’t need to create abstraction noise around it.

Thoughts?

**Comment by xivSolutions** [comment]
Seems like it would be handy, if the total transaction was a series of simple inserts/updates etc, to be able to go .begin/.end somehow. Anything beyond that though would make more sense as a SQL file (which was my initial reaction as well). 

I think only if it could be done without adding too much noise/complexity.

**Comment by dmfay** [comment]
Yeah, I'm thinking more along the lines of what John mentioned -- I'm not at all averse to procedures or executable scripts as a matter of principle, but in many cases I'd prefer to leverage the generated read/write methods for consistency's sake (or, alternatively, I have something that would be hellish spaghetti if expressed in SQL).

One other thing I'd like to be able to do is run a test in a transaction that gets rolled back in afterEach().

**Comment by xivSolutions** [comment]
@dmfay and @robconery  - have you messed about with how this might be accomplished yet? I have been travelling extensively this month, and not able to do any actual code work at the moment (grrr). Do we think it can be done without making a mess of the existing code or adding excessive complexity? 

I wonder if an independent module could be used for transactions?

**Comment by robconery** [comment]
I’ve been thinking about it quite a bit. The simplest is a promise chain or to wrap in Async somehow - the hard part is making the query “aware” that’s in a tx so it only returns some type of command.

My gut feeling is that this is more work then we think…

One idea would be to wrap up a “context” - something that clones the current DB and allows you to build on top of it:

var tx = db.createTransaction() //clones the current DB with tables

tx.myTable.insert({..})

tx.execute()

Thoughts? 



On July 1, 2015 at 9:12:40 AM, John Atten (notifications@github.com) wrote:

@dmfay and @robconery - have you messed about with how this might be accomplished yet? I have been travelling extensively this month, and not able to do any actual code work at the moment (grrr). Do we think it can be done without making a mess of the existing code or adding excessive complexity?

I wonder if an independent module could be used for transactions?

**Comment by dmfay** [comment]
I played around with it a bit yesterday, and yeah it's not a trivial addition. Opening and closing a transaction are both easy enough, but you have to ensure that all your transactional queries run on the same pg.Client (and that nothing else uses your client either!).

Cloning is definitely one way of doing it, and dirac (https://github.com/jrf0110/dirac) has what looks to be a good, clean implementation of it for what they do, but they're more of a pure lightweight O/RM than a MyBatis-style data mapper.

I think it might be possible to avoid the overhead of cloning though, if somehow we could force runner.query to use a particular client -- if beginning a transaction were to reserve a client and return a token by which it could be retrieved and run against, maybe? Although I don't think that'd work out very well for backwards-compatible APIs....

As for third-party modules, there's https://github.com/goodybag/node-pg-transaction but I think we'd still have the problem of keeping the dedicated client reserved.

**Comment by robconery** [comment]
I don’t think we need a full cloning operation necessarily - maybe just a table load - which is actually just an array copy since we already have a tables array.

It’s not the fastest thing in the world - but the nice thing is that we can handle connections explicitly with the tx object. Given that we have only one thread running per process, we could also just have a transaction object ready to go from spin up, so there’s no hit when wanting to execute one (we could set the props on the prototype and new up a TX object as needed).

I *really* want to avoid syntax/abstraction wonkiness and promises. I hate them.



On July 1, 2015 at 9:52:40 AM, Dian Fay (notifications@github.com) wrote:

I played around with it a bit yesterday, and yeah it's not a trivial addition. Opening and closing a transaction are both easy enough, but you have to ensure that all your transactional queries run on the same pg.Client (and that nothing else uses your client either!).

Cloning is definitely one way of doing it, and dirac (https://github.com/jrf0110/dirac) has what looks to be a good, clean implementation of it for what they do, but they're more of a pure lightweight O/RM than a MyBatis-style data mapper.

I think it might be possible to avoid the overhead of cloning though, if somehow we could force runner.query to use a particular client -- if beginning a transaction were to reserve a client and return a token by which it could be retrieved and run against, maybe? Although I don't think that'd work out very well for backwards-compatible APIs....

As for third-party modules, there's https://github.com/goodybag/node-pg-transaction but I think we'd still have the problem of keeping the dedicated client reserved.

**Comment by vitaly-t** [comment]
>I *really* want to avoid syntax/abstraction wonkiness and promises. I hate them.

And that is *really* a subjective and narrow look at things that won't help other developers here, and won't help you either, in the long run. Sometimes it is useful to meditate on the new technologies to see what is really good, instead of just scorning them.

I am the author of [pg-promise](https://github.com/vitaly-t/pg-promise), and I can tell you that when working with databases and NodeJS, promises offer absolutely [the best syntax for writing transactions](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#transactions), because the logic of transactions maps perfectly 1:1 to the logic of promises.

And since the logic of **connect->query->disconnect** also maps into the promise chain naturally, the combination of the two allow a perfect symbiosis for managing connections and transactions in a single chain. No other approach can do the same.

**Comment by robconery** [comment]
> I can tell you from long experience that when working with databases and NodeJS, promises offer absolutely the best syntax for writing transactions

Yes, please tell me about my narrow view of things :p.

You want to know why I dislike promises? This:
https://github.com/TryGhost/Ghost/blob/master/core/server/index.js#L142

I understand other people like them, I understand *you* like them and have dropped by to pimp your library and diss me at the same time, which is great. It's also pretty bad form.

I'm happy you like your library; use yours, don't use mine.
